on:
  schedule:
    - cron: "0 0 * * 6"
  # push:  # 可选：推送代码时也触发，便于测试
  #   branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-generate:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 运行器

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12" # 指定你的 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 安装你的第三方库
      - name: Send Issue
        env: # Set the secret as an input
          CLIENT_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: python month_trend.py
